#!/usr/bin/env bash
#
# Checks that all non-merge commit messages reference a Github Issue.
#

# regex to validate in commit msg
commit_regex='(Issue #[0-9]+|merge)'
error_msg="Aborting commit. Your commit message is missing either a Github Issue ('Issue #131') or 'Merge'"

if ! grep -iqE "$commit_regex" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi
