#!/usr/bin/env bash
#
# Attempts to extract Github issue from the branch name, and to appends it
# to the commit message.
#
append_feature_number_to_commit_message() {
    BRANCH=$(git branch | grep '*' | sed 's/* //')
    if [[ $BRANCH =~ feature\/([0-9]+).* ]]; then
        FEATURE_NUMBER="${BASH_REMATCH[1]}"
        echo -e "$(cat "$1")\n\nIssue #$FEATURE_NUMBER " > "$1"
    fi
}

case "$2,$3" in
  message,)
    append_feature_number_to_commit_message "$1" ;;
  ,)
    append_feature_number_to_commit_message "$1" ;;
  *) ;;
esac